services:
  - type: web
    name: tracknet-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BACKEND_CORS_ORIGINS
        value: '["https://tracknet-seven.vercel.app","http://localhost:5173"]'
      - key: DATABASE_URL
        fromDatabase:
          name: tracknet-db
          property: connectionString

databases:
  - name: tracknet-db
    plan: free
